### ISSUE TITLE
failed to get consensus because argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by terrytangyuan** [caicloud/ftlib#69]
I am getting the following error when trying to use `custom_bind_addr` in `BasicFTLib` (I am using it in ElasticDL [here](https://github.com/sql-machine-learning/elasticdl/blob/develop/elasticdl/python/collective_ops/communicator.py#L31), please double check if I am passing it correctly).

```
log file: /tmp/memberlist.log
joining with ips:
11.238.113.27
WARNING:root:failed to get consensus because argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/elasticdl/python/worker/main.py", line 69, in <module>
    main()
  File "/elasticdl/python/worker/main.py", line 63, in main
    set_parallelism=True,
  File "/elasticdl/python/worker/worker.py", line 122, in __init__
    self._init_from_args(args)
  File "/elasticdl/python/worker/worker.py", line 159, in _init_from_args
    if self._distribution_strategy == DistributionStrategy.ALLREDUCE
  File "/elasticdl/python/collective_ops/communicator.py", line 31, in __init__
    "custom_bind_addr": socket.gethostbyname(socket.gethostname()),
  File "/usr/local/lib/python3.6/dist-packages/ftlib/impl.py", line 100, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/ftlib/impl.py", line 302, in build
    raise Exception("building consensus failed")
Exception: building consensus failed
```
The `socket.gethostbyname(socket.gethostname())` seems to be successful since I also used it [here](https://github.com/sql-machine-learning/elasticdl/blob/develop/elasticdl/python/collective_ops/communicator.py#L99) which had no problem.

**Comment by terrytangyuan** [comment]
Changing log level to DEBUG only generates this additional log message: `Setting Bind Address as 11.238.113.75`. Everything else is the same.

**Comment by zw0610** [comment]
I believe it's a bug introduced since the last pr. Let me try to fix it today.

**Comment by skydoorkai** [comment]
Got the failure below, not sure if related to this issue.

```
Setting Bind Address as 11.68.115.84
log file: /tmp/memberlist.log
[2020-03-27 09:29:33,130] [WARNING] [communicator.py:37:__init__] Retry building consensus...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/elasticdl/elasticdl/python/worker/main.py", line 76, in <module>
    main()
  File "/elasticdl/elasticdl/python/worker/main.py", line 70, in main
    set_parallelism=True,
  File "/elasticdl/elasticdl/python/worker/worker.py", line 122, in __init__
    self._init_from_args(args)
  File "/elasticdl/elasticdl/python/worker/worker.py", line 159, in _init_from_args
    if self._distribution_strategy == DistributionStrategy.ALLREDUCE
  File "/elasticdl/elasticdl/python/collective_ops/communicator.py", line 39, in __init__
    known_addr_list=list(self._get_peer_set(service_name))
  File "/usr/local/lib/python3.6/dist-packages/ftlib/impl.py", line 137, in manual_join
    return self.consensus.manual_join(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ftlib/consensus/gossip/impl.py", line 85, in manual_join
    self.joined = self._join(known_addr_list, wait_time=wait_time)
  File "/usr/local/lib/python3.6/dist-packages/ftlib/consensus/gossip/impl.py", line 92, in _join
    assert addr_list_len >= 1
AssertionError
```

**Comment by zw0610** [comment]
> Got the failure below, not sure if related to this issue.
> 
> ```
> Setting Bind Address as 11.68.115.84
> log file: /tmp/memberlist.log
> [2020-03-27 09:29:33,130] [WARNING] [communicator.py:37:__init__] Retry building consensus...
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/elasticdl/elasticdl/python/worker/main.py", line 76, in <module>
>     main()
>   File "/elasticdl/elasticdl/python/worker/main.py", line 70, in main
>     set_parallelism=True,
>   File "/elasticdl/elasticdl/python/worker/worker.py", line 122, in __init__
>     self._init_from_args(args)
>   File "/elasticdl/elasticdl/python/worker/worker.py", line 159, in _init_from_args
>     if self._distribution_strategy == DistributionStrategy.ALLREDUCE
>   File "/elasticdl/elasticdl/python/collective_ops/communicator.py", line 39, in __init__
>     known_addr_list=list(self._get_peer_set(service_name))
>   File "/usr/local/lib/python3.6/dist-packages/ftlib/impl.py", line 137, in manual_join
>     return self.consensus.manual_join(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/ftlib/consensus/gossip/impl.py", line 85, in manual_join
>     self.joined = self._join(known_addr_list, wait_time=wait_time)
>   File "/usr/local/lib/python3.6/dist-packages/ftlib/consensus/gossip/impl.py", line 92, in _join
>     assert addr_list_len >= 1
> AssertionError
> ```

I believe not. It looks `known_addr_list` eventually passed into `Gossip._join` is an empty list: `[]`.
